# -*- coding: utf-8 -*-
"""Task 2 |  Stock Portfolio Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pObOJwd_rTav2KyxCIJ7YxJd5xVLyt_
"""

# ========================================
#   TASK 2: Stock Portfolio Tracker
# ========================================

"""
 Summary:
Calculates the total investment value based on predefined stock prices and user input.

 Key Concepts:
 Dictionary to store stock prices
 User input handling
 Basic arithmetic
 Optional file saving
"""

# Predefined stock prices
stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "MSFT": 300,
    "AMZN": 140,
    "GOOGL": 125
}

portfolio = {}
total_value = 0

print("\n=========Welcome to Stock Portfolio Tracker ==========")
print("Available Stocks:", ", ".join(stock_prices.keys()))

while True:
    stock = input("Enter stock symbol (or 'done' to finish): ").upper()
    if stock == "DONE":
        break
    if stock not in stock_prices:
        print("Invalid stock symbol!")
        continue
    qty = int(input(f"Enter quantity of {stock}: "))
    portfolio[stock] = portfolio.get(stock, 0) + qty

print("\n------ Your Portfolio: ---------")
for stock, qty in portfolio.items():
    value = stock_prices[stock] * qty
    total_value += value
    print(f"{stock} - {qty} shares - ${value}")

print("\n Total Investment Value: $", total_value)

# Save to file
with open("portfolio.txt", "w") as f:
    f.write("Your Portfolio:\n")
    for stock, qty in portfolio.items():
        f.write(f"{stock} - {qty} shares - ${stock_prices[stock] * qty}\n")
    f.write(f"Total Investment Value: ${total_value}")

print(" Portfolio saved to portfolio.txt")